Alerts user if the client cannot connect to airsim
jenniferolenchak/VisualInspectionDeepLearning pull request #30
Opened 2023-02-21 18:45 UTC by brandonspangler2

Prompts user to follow instructions upon failure to initialize.

2023-02-27 19:18 UTC, jenniferolenchak requested changes

2023-02-27 19:18 UTC, jenniferolenchak commented on Application/LaunchScreen.py
> +    def setText(self):
Needs a more specific function name

2023-02-27 19:18 UTC, jenniferolenchak commented on Application/LaunchScreen.py
>          self.ui.button_InitializeClient.setText("Initializing Client...")
The text does not switch to "Initializing client" until after it has already failed to connect. We may need to use the same app refresh function from the loading screen here so it is forced to updated.

2023-02-27 19:18 UTC, jenniferolenchak commented on Application/LaunchScreen.py
> +        self.ui.button_InitializeClient.setText("Failed to Start. Follow the above instructions.")
When the text of the button was changed, the text extended beyond the button's size and was unreadable.

The text of the button itself should change to be something like "Retry Client Initialization" and a separate pop-up box and/or label should appear specifying that there was an error

2023-02-28 21:23 UTC, brandonspangler2 commented on Application/LaunchScreen.py
> +    def setText(self):
Refactored to remove function.

2023-02-28 21:23 UTC, brandonspangler2 commented on Application/LaunchScreen.py
>          self.ui.button_InitializeClient.setText("Initializing Client...")
It is switching properly on my machine. I added in the forced refresh, see if that works.

2023-02-28 21:24 UTC, brandonspangler2 commented on Application/LaunchScreen.py
> +        self.ui.button_InitializeClient.setText("Failed to Start. Follow the above instructions.")
Added popup window alerting user of error and set the button text to 'Retry Client Initialization.'

2023-03-02 02:58 UTC, jenniferolenchak commented on Application/LaunchScreen.py
>          self.ui.button_InitializeClient.setText("Initializing Client...")
It works now!

2023-03-02 03:15 UTC, jenniferolenchak commented on Application/LaunchScreen.py
> +        self.ui.button_InitializeClient.setText("Failed to Start. Follow the above instructions.")
![image](https://user-images.githubusercontent.com/59713234/222321043-b945968c-ad0a-4805-a2b9-ac071fd66313.png)

1. Format the text/window to be in the center. Either left-align the text or manually set the window size to have the error message seemingly in the center [see above for issue]
2. Set the window title to be "Error" so it does not default to saying "python3"
3. Set the error window icon to match our main window icon
4. For the error message itself, can we expand the user directions? Maybe something like:
`"Error initializing the client. Before initializing the client, please ensure that you have launched the AirSim Unreal Engine Environment and that the quadrotor drone is loaded completely. Select "Retry Client Initialization" to try again.`

For the main window, items 2 and 3 are done as such:
    `stackedWidget.setWindowTitle("DroneVQA")`
    `stackedWidget.setWindowIcon(QIcon("Images/Logos/logo_drone_only.png"))`

and the result is that the top of the main window appears as such:
![image](https://user-images.githubusercontent.com/59713234/222321712-73718936-78cf-4f10-9162-b627764fc6b5.png)

2023-03-02 05:56 UTC, jenniferolenchak commented on Application/LaunchScreen.py
> +        self.ui.button_InitializeClient.setText("Failed to Start. Follow the above instructions.")
@brandonspangler2

2023-03-02 19:28 UTC, brandonspangler2 commented on Application/LaunchScreen.py
> +        self.ui.button_InitializeClient.setText("Failed to Start. Follow the above instructions.")
I believe they are all fixed. The popup looks different on Mac so cannot be 100% sure.

2023-03-17 02:36 UTC, jenniferolenchak approved these changes

2023-03-17 02:36 UTC, merged