Move based on current position
jenniferolenchak/VisualInspectionDeepLearning pull request #47
Opened 2023-03-20 20:29 UTC by brandonspangler2

Drone moves relative to its current position rather than the starting position.

2023-03-20 21:04 UTC, jenniferolenchak commented
Ideally rework to allow for continuous movement when motion buttons are held down

2023-03-20 21:10 UTC, jenniferolenchak commented on Application/AirSimControl.py
> +from threading import Timer
Is this still needed?

2023-03-20 21:13 UTC, jenniferolenchak requested changes

2023-03-20 21:13 UTC, jenniferolenchak commented on Application/AirSimControl.py
> +    def startDroneMovement(self, command, moveButtons):
Is moveButtons parameter still needed here?

2023-03-20 21:13 UTC, jenniferolenchak commented on Application/AirSimControl.py
> +    def stopDroneMovement(self, moveButtons):
Is moveButtons parameter still needed here?

2023-03-20 21:13 UTC, jenniferolenchak commented on Application/AirSimControl.py
> +
Remove extra space?

2023-03-20 21:15 UTC, jenniferolenchak requested changes

2023-03-20 21:15 UTC, jenniferolenchak commented on Application/AirSimControl.py
>          self.client.moveByVelocityAsync(0, 0, 0, 3)
Should this be 3?

2023-03-20 21:18 UTC, brandonspangler2 commented on Application/AirSimControl.py
> +from threading import Timer
Removed

2023-03-20 21:19 UTC, brandonspangler1 commented on Application/AirSimControl.py
> +    def startDroneMovement(self, command, moveButtons):
removed

2023-03-20 21:19 UTC, brandonspangler2 commented on Application/AirSimControl.py
> +    def stopDroneMovement(self, moveButtons):
reverted

2023-03-20 21:20 UTC, brandonspangler2 commented on Application/AirSimControl.py
> +
removed

2023-03-20 21:28 UTC, brandonspangler1 commented on Application/AirSimControl.py
>          self.client.moveByVelocityAsync(0, 0, 0, 3)
That third parameter is for duration so the method is stopping drone movement for 3 seconds. Git is telling me you were the last person to edit that line but I tried it at 1 and didn't see a difference. I am assuming on release of the button it stops the movement but then moving again overrides this so the drone is never stuck for three seconds and as such we should probably leave it at three.

2023-03-21 07:28 UTC, jenniferolenchak approved these changes

2023-03-21 07:28 UTC, merged